export const GET_WIKIPEDIA_START = 'GET_WIKIPEDIA_START';
export const GET_WIKIPEDIA_SUCCESS = 'GET_WIKIPEDIA_SUCCESS';
export const GET_WIKIPEDIA_FAIL = 'GET_WIKIPEDIA_FAIL';

export const GET_NYTIMES_START = 'GET_NYTIMES_START';
export const GET_NYTIMES_SUCCESS = 'GET_NYTIMES_SUCCESS';
export const GET_NYTIMES_FAIL = 'GET_NYTIMES_FAIL';
